name: build_and_release
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: sh
            name: linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: build
        run: ./build_mtree.${{ matrix.extension }}
      - name: package addon
        run: python3.11 .github/scripts/setup_addon.py
      - name: Display generated files
        run: ls -R ./tmp
      - name: upload zipped addon
        uses: actions/upload-artifact@v4
        with:
          name: modular_tree_${{ matrix.name }}
          path: ./tmp/*.zip
      - name: Get version
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      STATUS: ${{ !endsWith(github.ref, 'master') && 'alpha' || '' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
      - name: Get version
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Update release
        uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./modular_tree_linux/modular_tree_${{ steps.vars.outputs.version }}_linux.zip
          release: Release V${{ steps.vars.outputs.version }}${{ env.STATUS }}
          tag: ${{ steps.vars.outputs.version }}${{ env.STATUS }}
          replace: true
          message: V${{ steps.vars.outputs.version }}
          body: ''

